# base configuration
train_path: 'ADNI_MRI2PET/train'
eval_path: 'ADNI_MRI2PET/test'
train_bc: 1
eval_bc: 1
img_sz: [160, 160, 96]
num_epochs: 200

# train process configuration
val_inter: 4
save_inter: 5


# accelerate config
split_batches: False
mixed_precision: 'fp16'
log_with: 'tensorboard'
project_dir: 'weights'
gradient_accumulation_steps: 1
is_debug: True